---
title: "Simulación de Montecarlo - GBM"
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
    navbar:
      - { title: "Inicio", href: "https://tudatapartner.cl/", align: right}
      - { icon: "fa-facebook", href: "https://www.facebook.com/Tudatapartner", align: right }
      - { icon: "fa-instagram", href: "https://www.instagram.com/tudatapartner/", align: right}
      - { icon: "fa-linkedin", href: "https://www.linkedin.com/company/71505235/admin/", align: right}


runtime: shiny
---


```{r setup, include=FALSE}

library("highcharter")

```


Sidebar {.sidebar data-width=300}
=====================================
Parametros de la Simulacion



```{r}


sliderInput(inputId = "S0",
                  label = "Valor Inicial",
                  min = 1,
                  max = 2000,
                  value = 860)

 sliderInput(inputId = "t",
                  label = "Horizonte de Simulación",
                  min = 1,
                  max = 1400,
                  value = 100)

 sliderInput(inputId = "nsim",
                  label = "Número de Simulaciones",
                  min = 1,
                  max = 1000,
                  value = 400)
 
  sliderInput(inputId = "sigma",
                  label = "Volatilidad",
                  min = 0,
                  max = 1,
                  value = 0.05)
  
    sliderInput(inputId = "mu",
                  label = "Mu",
                  min = -2,
                  max = 2,
                  value = 0, 
                 step = 0.1)
    

```


Visualización {data-icon="fa-signal"}
===================================== 

Column {data-width=400}
-------------------------------------
    
### Trayectorias

```{r}
renderPlot({
  
gbm_vec <- function(nsim, t , mu, sigma , S0 , dt) {
  # matrix of random draws - one for each day for each simulation
  epsilon <- matrix(rnorm(t*nsim), ncol = nsim, nrow = t)  
  # get GBM and convert to price paths
  gbm <- exp((mu - sigma * sigma / 2) * dt + sigma * epsilon * sqrt(dt))
  gbm <- apply(rbind(rep(S0, nsim), gbm), 2, cumprod)
  return(gbm)
}

nsim <- input$nsim
t <- input$t
mu <- input$mu
sigma <- input$sigma
S0 <- input$S0
dt <- 1/254


gbm <- gbm_vec(nsim, t, mu, sigma, S0,dt)

gbm_df <- as.data.frame(gbm)

# Plotting ----------------------------------------------------------------

library(ggplot2)
library(reshape2)
library(hrbrthemes)

gbm_df$Periodos <- 1:(t+1)

plot<- melt(gbm_df,id.vars = "Periodos")



ggplot(plot,aes(x=Periodos, y= value, group = variable,color = value)) +
  geom_line(show.legend = FALSE) + 
  xlab("Periodos") + 
  ylab("Valor")+ 
  theme_ipsum_rc() + 
  ggtitle("Movimiento Geométrico Browniano",subtitle = paste(nsim,"Simulaciones")) + 
    scale_color_gradient2(midpoint = input$S0*exp(input$mu*(1/264)), low = "red",
                       high = "blue" , mid = "#7f7f7f")

  })

```

Column {data-width=200}
-------------------------------------
    
### Gráfico de Densidad

```{r}
renderHighchart({
  
gbm_vec <- function(nsim, t , mu, sigma , S0 , dt) {
  # matrix of random draws - one for each day for each simulation
  epsilon <- matrix(rnorm(t*nsim), ncol = nsim, nrow = t)  
  # get GBM and convert to price paths
  gbm <- exp((mu - sigma * sigma / 2) * dt + sigma * epsilon * sqrt(dt))
  gbm <- apply(rbind(rep(S0, nsim), gbm), 2, cumprod)
  return(gbm)
}

nsim <- input$nsim
t <- input$t
mu <- input$mu
sigma <- input$sigma
S0 <- input$S0
dt <- 1/254
print(getwd())


gbm <- gbm_vec(nsim, t, mu, sigma, S0,dt)

gbm_df <- as.data.frame(gbm)

# Plotting ----------------------------------------------------------------

library(ggplot2)
library(reshape2)

gbm_df$Periodos <- 1:(t+1)
  
hchart(
    density(gbm[t,]), 
    type = "area", name = "Weight"
  ) %>%hc_xAxis(reversed = FALSE) %>% 
  hc_chart(inverted = TRUE) %>% 
  hc_title(text = paste("Densidad Horizonte", input$t)) %>% 
  hc_add_theme(hc_theme_538())
  

  })

```

